apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-app-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/learnawsaps/desafio12.git'
    targetRevision: HEAD
    path: '/home/gardener/D15/charts/mi-chart/'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
